version: "3.6"

services:
  pptpd:
    build: ./pptpd
    container_name: pptpd
    volumes:
      - ./pptpd/pptpd.conf:/etc/pptpd.conf
      - ./pptpd/pptpd-options.conf:/etc/ppp/pptpd-options
      - ./pptpd/chap-secrets:/etc/ppp/chap-secrets
    privileged: true
    network_mode: host
    restart: always
    ports:
      - 0.0.0.0:1723:1723
  pi_admin_backend:
    build: ./pi-admin/backend
    container_name: pi_admin_backend
    volumes:
      - ./pi-admin/backend:/var/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pptpd/pptpd.conf:/config/pptpd/pptpd.conf
      - ./pptpd/pptpd-options.conf:/config/pptpd/pptpd-options
      - ./pptpd/chap-secrets:/config/pptpd/chap-secrets
      - ./minidlna/config:/config/minidlna
      - ./pi-admin/backend/config:/config/admin/config
      - ./pi-admin/backend/env:/config/admin/env
      - ./pi-admin/frontend/src/environments/:/config/admin/frontend
      - ./docker-compose.yml:/config/host/docker/docker-compose.yml
    privileged: true
    restart: always
    ports:
      - 3000:3000
  pi_admin_frontend:
    build: ./pi-admin/frontend
    container_name: pi_admin_frontend
    volumes:
      - ./pi-admin/frontend:/var/app/frontend
    restart: always
    ports:
      - 4200:4200
  minidlna:
    build: ./minidlna
    container_name: minidlna
    restart: always
    volumes:
      - ./minidlna/config/minidlna.conf:/etc/minidlna.conf
      - /storage/media/Video:/media:ro
    ports:
      - 1900/udp
      - 8200/tcp
    network_mode: host
  deluge:
    #build: ./deluge
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # - ./etc:/etc
      - /storage/media/Video:/downloads
      - /storage/media/Torrents:/torrents
      - /storage/media/.incompleted:/incompleted
      - ./deluge/config:/config
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946/udp
    network_mode: host
