menu:
  multimedia:
    items:
    #   nextcloud:
    #     type: configuration
    #     title: NextCloud
    #     icon: cloud
    #     route: next-cloud
    #     configFiles:

      nextcloud-external:
        type: external
        title: 'Open NextCloud'
        path: https://nextcloud.com/
        icon: cloud_circle
