menu:
  multimedia:
    items:
    #   torrent-transmission:
    #     type: configuration
    #     title: Transmission
    #     icon: device_hub
    #     route: transmission-config
    #     configFiles:
    #       - transmission_main

      torrent-transmission-panel:
        type: iframe
        route: transmission
        title: 'Open Transmission'
        path: http://localhost:9091
        icon: device_hub

